SELECT  P.NAME																PRODUCT_NAME
		, P.LISTPRICE
		, PSB.NAME															RODUCT_SUBCATEGORY
		, PC.NAME															PRODUCT_CATEGORY
		, AVG(P.LISTPRICE) OVER(PARTITION BY PC.NAME)						AVG_PRICE_BY_CATEGORY
		, AVG(P.LISTPRICE) OVER(PARTITION BY PC.NAME, PSB.NAME)				AVG_PRICE_BY_CATEGORY_AND_SUBCATEGORY
		, P.LISTPRICE - AVG(P.LISTPRICE) OVER(PARTITION BY PC.NAME)			PRODUCT_VS_CATEGORY_DELTA
FROM	PRODUCTION.PRODUCT								P
INNER	JOIN PRODUCTION.PRODUCTSUBCATEGORY				PSB
ON P.PRODUCTSUBCATEGORYID = PSB.PRODUCTSUBCATEGORYID
INNER	JOIN PRODUCTION.PRODUCTCATEGORY					PC
ON PSB.PRODUCTCATEGORYID = PC.PRODUCTCATEGORYID
GO

