SELECT	P.NAME					PRODUCT_NAME
		, P.LISTPRICE
		, PSB.NAME				PRODUCT_SUBCATEGORY
		, PC.NAME				PRODUCT_CATEGORY
		, PRICE_RANK = ROW_NUMBER() OVER(ORDER BY P.LISTPRICE DESC)
		, CATEGORY_PRICE_RANK = ROW_NUMBER() OVER(PARTITION BY PC.NAME ORDER BY P.LISTPRICE DESC)
		, CATEGORY_PRICE_RANK_WITH_RANK = RANK() OVER(PARTITION BY PC.NAME ORDER BY P.LISTPRICE DESC)
		, CATEGORY_PRICE_RANK_WITH_DENSE_RANK = DENSE_RANK() OVER(PARTITION BY PC.NAME ORDER BY P.LISTPRICE DESC)
		, CASE
			WHEN DENSE_RANK() OVER(PARTITION BY PC.NAME ORDER BY P.LISTPRICE DESC) BETWEEN 1 AND 5 THEN 'Yes'
			ELSE 'No'
		  END AS				TOP_5_PRICE_IN_CATEGORY
FROM	PRODUCTION.PRODUCT								P
INNER	JOIN PRODUCTION.PRODUCTSUBCATEGORY				PSB
ON P.PRODUCTSUBCATEGORYID = PSB.PRODUCTSUBCATEGORYID
INNER	JOIN PRODUCTION.PRODUCTCATEGORY					PC
ON PSB.PRODUCTCATEGORYID = PC.PRODUCTCATEGORYID


