SELECT	PURCHASEORDERID	
		, VENDORID
		, ORDERDATE
		, TAXAMT
		, FREIGHT
		, TOTALDUE
		, SALES_RANKING
FROM (SELECT	PURCHASEORDERID	
				, VENDORID
				, ORDERDATE
				, TAXAMT
				, FREIGHT
				, TOTALDUE
				, DENSE_RANK() OVER(PARTITION BY VENDORID ORDER BY TOTALDUE DESC) AS SALES_RANKING
				FROM	PURCHASING.PURCHASEORDERHEADER
	) SUBQUERY
WHERE SALES_RANKING BETWEEN 1 AND 3


