SELECT	BUSINESSENTITYID
		, JOBTITLE
		, VACATIONHOURS
		, MAX_VACATION_HOURS = (SELECT MAX(VACATIONHOURS) FROM HUMANRESOURCES.EMPLOYEE) 
FROM	HUMANRESOURCES.EMPLOYEE
--------------------------------//---------------------------------------//----------------------------//--------------------------
SELECT	BUSINESSENTITYID
		, JOBTITLE
		, VACATIONHOURS
		, MAX_VACATION_HOURS = (SELECT MAX(VACATIONHOURS) FROM HUMANRESOURCES.EMPLOYEE) 
		, PERCENT_OF_MAX_VACATION_HOURS = (VACATIONHOURS  * 1.0) / (SELECT MAX(VACATIONHOURS) FROM HUMANRESOURCES.EMPLOYEE)
FROM	HUMANRESOURCES.EMPLOYEE
--------------------------------//---------------------------------------//----------------------------//----------------------------
SELECT	BUSINESSENTITYID
		, JOBTITLE
		, VACATIONHOURS
		, MAX_VACATION_HOURS = (SELECT MAX(VACATIONHOURS) FROM HUMANRESOURCES.EMPLOYEE) 
		, PERCENT_OF_MAX_VACATION_HOURS = (VACATIONHOURS  * 1.0) / (SELECT MAX(VACATIONHOURS) FROM HUMANRESOURCES.EMPLOYEE)
FROM	HUMANRESOURCES.EMPLOYEE
WHERE	(VACATIONHOURS  * 1.0) / (SELECT MAX(VACATIONHOURS) FROM HUMANRESOURCES.EMPLOYEE) > 0.80
--------------------------------//---------------------------------------//----------------------------//----------------------------




