SELECT	PURCHASEORDERID
		, VENDORID
		, ORDERDATE
		, TOTALDUE
		, NON_REJECTED_ITEMS = 
		(SELECT	COUNT(*)
FROM	PURCHASING.PURCHASEORDERDETAIL POD
WHERE	POD.PURCHASEORDERID = POH.PURCHASEORDERID	
AND	REJECTEDQTY <> 0)
FROM	PURCHASING.PURCHASEORDERHEADER POH
----------------------------------------------------------------
SELECT	POH.PURCHASEORDERID
		, POH.VENDORID
		, POH.ORDERDATE
		, POH.TOTALDUE
		, MOST_EXPENSIVE_ITEM = (
			SELECT	MAX(POD.UNITPRICE)
			FROM	PURCHASING.PURCHASEORDERDETAIL POD
			WHERE	POD.PURCHASEORDERID = POH.PURCHASEORDERID
		)
FROM	PURCHASING.PURCHASEORDERHEADER POH





