SELECT	POH.PURCHASEORDERID
		, POH.ORDERDATE
		, POH.SUBTOTAL
		, POH.TAXAMT
FROM	PURCHASING.PURCHASEORDERHEADER						POH
WHERE	EXISTS (
				SELECT	1
				FROM	PURCHASING.PURCHASEORDERDETAIL		POD
				WHERE	POH.PURCHASEORDERID = POD.PURCHASEORDERID
				AND	POD.ORDERQTY > 500
				)
ORDER BY	POH.PURCHASEORDERID		
--------------------------------------------------------------
SELECT	POH.*
FROM	PURCHASING.PURCHASEORDERHEADER						POH
WHERE	EXISTS (
				SELECT	1
				FROM	PURCHASING.PURCHASEORDERDETAIL		POD
				WHERE	POH.PURCHASEORDERID = POD.PURCHASEORDERID
				AND	POD.ORDERQTY > 500
				AND POD.UNITPRICE > 50.00
				)
ORDER BY	POH.PURCHASEORDERID	
--------------------------------------------------------------
SELECT	POH.*
FROM	PURCHASING.PURCHASEORDERHEADER						POH
WHERE	NOT EXISTS (
				SELECT	1
				FROM	PURCHASING.PURCHASEORDERDETAIL		POD
				WHERE	POH.PURCHASEORDERID = POD.PURCHASEORDERID
				AND		POD.REJECTEDQTY > 0
				)
ORDER BY	POH.PURCHASEORDERID	


